---
# file elkstack.yml
- hosts: servers
  sudo: yes

  vars_files:
   - vars/default.yml

  roles:
    - { role: environment }
    - { role: elasticsearch }
    - { role: logstash }
    - { role: nginx-kibana }
