---
# file elkstack.yml
- hosts: servers
  sudo: yes

  vars_files:
   - vars/default.yml

  roles:
    - { role: elasticsearch, tags: ["elasticsearch"] }
    - { role: logstash, tags: ["logstash"] }
    - { role: nginx-kibana, tags: ["nginx-kibana"] }
