- name: Create Kibana dir
  file: 
   path=/opt/kibana 
   state=directory

- name: Create Kibana log dir
  file: 
    path=/opt/kibana/logs 
    state=directory

- name: Get Kibana
  get_url: 
    url={{ kibana_url }} 
    dest=/tmp/kibana.tar.gz

- name: Unarchive kibana
  unarchive:
    src: /tmp/kibana.tar.gz
    dest: /opt/kibana/
    copy: no

- name: Kibana Permissions
  command: /bin/chown -R nginx.nginx /opt/kibana

- name: Create kibana init-script
  template:
    src=kibana.j2
    dest=/etc/init.d/kibana
    owner=root
    group=root
    mode=0755

- name: Enable kibana service
  service: 
    name=kibana
    enabled=yes
    state=started
