- name: Elasticsearch configuration
  template: 
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0644

- name: Install license plugin for ES
  shell: /usr/share/elasticsearch/bin/plugin install license

- name: Install Shield plugin for ES
  shell: /usr/share/elasticsearch/bin/plugin install shield

- name: Enable elasticsearch service
  service:
    name=elasticsearch
    enabled=yes
    state=started
