- name: Elasticsearch configuration
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify:
   - restart elasticsearch

- name: Enable elasticsearch service
  service: name=elasticsearch enabled=yes state=started
